baseURL = "https://manwe-io.github.io/"
languageCode = "en-us"
title = "Manwe Security Consulting"
theme = "learn"
RelativeURLs=true
CanonifyURLs=true

[params]
  pygmentsCodeFences = true
  pygmentsStyle="monokai"
    editURL = ""
  author = "Wes Widner"
  description = "Documentation for Manwe"
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false
  disableShortcutsTitle = false
  disableLanguageSwitchingButton = false
  disableBreadcrumb = true
  disableNextPrev = false
  ordersectionsby = "weight"
  themeVariant = "manwe"

[[menu.shortcuts]] 
  name = "<i class='fab fa-github'></i> Github repo"
  identifier = "ds"
  url = "https://github.com/manwe-io/manwe-io"
  weight = 10

[outputs]
  home = [ "HTML", "RSS", "JSON"]